### PR TITLE
client: limit maximum length for client ID to 133 bytes

### PR DESCRIPTION
**Pull request by thom311**
This is also the effective limit used by systemd-networkd.

### CODE REVIEW

**Comment by thom311** [comment]
One question is, whether 133 bytes is the right limit. Maybe 255 would be better? Dunno. WDYT?

**Comment by bengal** [comment]
> One question is, whether 133 bytes is the right limit. Maybe 255 would be better? Dunno. WDYT?

133 seems arbitrary. I think the client should accept the maximum length allowed by the protocol, which is 255.

**Comment by thom311** [comment]
in systemd, the limit was first 64 bytes ([[1]](https://github.com/systemd/systemd/commit/ba6c0fd6303c63576983c7be892d80d954c1e4c5)), later extended to 4+128 bytes ([[2]](https://github.com/systemd/systemd/commit/5bac5235934fabe5a3e6a9d47f4812f81034c427)).

This patch uses the same limit (+ 1, which in n-dhcp4 is for the type -- in systemd the type is passed separately).

I don't really mind either way.

**Comment by thom311** [comment]
merged a modified version to master, that accepts client ids from 2 to 255 bytes length.

**Pull request closed without merging**
